- name: Install Repo Zabbix 5.0
  yum:
    name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
    state: present

- name: Install Zabbix Agent and Server
  yum:
    name: "{{ zabbix_server_packages }}"
    state: latest
  vars:
   zabbix_server_packages:
   - zabbix-server-mysql 
   - zabbix-agent  

- name: Enable Red Hat Software Collections
  yum:
    name: centos-release-scl
    state: latest

- name: Enable Zabbix-Frontend repository
  replace:
    path: /etc/yum.repos.d/zabbix.repo
    after: 'zabbix-frontend'
    before: 'gpgkey'
    regexp: '^enabled=0'
    replace: enabled=1


- name: Install Zabbix frontend
  yum:
    name: "{{ zabbix_frontend_packages }}"
    state: latest
  vars:
   zabbix_frontend_packages:
    - zabbix-web-mysql-scl 
    - zabbix-apache-conf-scl
